# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    twig:
        mode: lazy
    filter_sets:
        cache: ~
        miniature:
            quality: 75
            filters:
                thumbnail: { size: [250, 250], mode: outbound }
                # fixed:
                #     width: 525
                #     height: 400
        about:
            quality: 80
            filters:
                thumbnail: { size: [600, 450], mode: outbound }
                # fixed:
                #     width: 600
                #     height: 450
        show:
            quality: 80
            filters:
                fixed:
                    width: 525
                    height: 400
        index:
            quality: 80
            filters:
                thumbnail: { size: [800, 600], mode: outbound }
                scale:
                    to: 0.2
        
        slide:
            quality: 80
            filters:
                #thumbnail: { size: [800, 600], mode: outbound }
                fixed:
                    width: 525
                    height: 400

        best:
            quality: 80
            filters:
                #thumbnail: { size: [800, 600], mode: outbound }
                fixed:
                    width: 382
                    height: 250
        
        activite:
            quality: 75
            filters:
                thumbnail: { size: [250, 400], mode: outbound }
                # fixed:
                #     width: 525
                #     height: 400
