vich_uploader:
    db_driver: orm

    metadata: 
        type: attribute

    mappings:
        services:
            uri_prefix: '%app.path.services_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.services_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        
        home: 
            uri_prefix: '%app.path.home_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.home_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        
        about: 
            uri_prefix: '%app.path.about_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.about_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        
        slide: 
            uri_prefix: '%app.path.gallery_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.gallery_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        thumbnail: 
            uri_prefix: '%app.path.home_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.home_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

